<?php

namespace Database\Seeders;

use App\Core\RBAC\Models\Permission;
use App\Core\RBAC\Models\Role;
use Illuminate\Database\Seeder;

class CoreRolesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $permissions = [
            ['name' => 'View Company', 'slug' => 'core.company.view', 'group' => 'core'],
            ['name' => 'Manage Company', 'slug' => 'core.company.manage', 'group' => 'core'],
            ['name' => 'View Roles', 'slug' => 'core.roles.view', 'group' => 'core'],
            ['name' => 'Manage Roles', 'slug' => 'core.roles.manage', 'group' => 'core'],
            ['name' => 'View Permissions', 'slug' => 'core.permissions.view', 'group' => 'core'],
            ['name' => 'Manage Permissions', 'slug' => 'core.permissions.manage', 'group' => 'core'],
            ['name' => 'Manage Users', 'slug' => 'core.users.manage', 'group' => 'core'],
            ['name' => 'Manage Settings', 'slug' => 'core.settings.manage', 'group' => 'core'],
            ['name' => 'View Notifications', 'slug' => 'core.notifications.view', 'group' => 'core'],
            ['name' => 'Manage Notifications', 'slug' => 'core.notifications.manage', 'group' => 'core'],
            ['name' => 'View Attachments', 'slug' => 'core.attachments.view', 'group' => 'core'],
            ['name' => 'Manage Attachments', 'slug' => 'core.attachments.manage', 'group' => 'core'],
            ['name' => 'View Audit Logs', 'slug' => 'core.audit_logs.view', 'group' => 'core'],
            ['name' => 'Manage Audit Logs', 'slug' => 'core.audit_logs.manage', 'group' => 'core'],

            ['name' => 'View Partners', 'slug' => 'core.partners.view', 'group' => 'master_data'],
            ['name' => 'Manage Partners', 'slug' => 'core.partners.manage', 'group' => 'master_data'],
            ['name' => 'View Contacts', 'slug' => 'core.contacts.view', 'group' => 'master_data'],
            ['name' => 'Manage Contacts', 'slug' => 'core.contacts.manage', 'group' => 'master_data'],
            ['name' => 'View Addresses', 'slug' => 'core.addresses.view', 'group' => 'master_data'],
            ['name' => 'Manage Addresses', 'slug' => 'core.addresses.manage', 'group' => 'master_data'],
            ['name' => 'View Products', 'slug' => 'core.products.view', 'group' => 'master_data'],
            ['name' => 'Manage Products', 'slug' => 'core.products.manage', 'group' => 'master_data'],
            ['name' => 'View Taxes', 'slug' => 'core.taxes.view', 'group' => 'master_data'],
            ['name' => 'Manage Taxes', 'slug' => 'core.taxes.manage', 'group' => 'master_data'],
            ['name' => 'View Currencies', 'slug' => 'core.currencies.view', 'group' => 'master_data'],
            ['name' => 'Manage Currencies', 'slug' => 'core.currencies.manage', 'group' => 'master_data'],
            ['name' => 'View Units of Measure', 'slug' => 'core.uoms.view', 'group' => 'master_data'],
            ['name' => 'Manage Units of Measure', 'slug' => 'core.uoms.manage', 'group' => 'master_data'],
            ['name' => 'View Price Lists', 'slug' => 'core.price_lists.view', 'group' => 'master_data'],
            ['name' => 'Manage Price Lists', 'slug' => 'core.price_lists.manage', 'group' => 'master_data'],

            ['name' => 'View Sales Leads', 'slug' => 'sales.leads.view', 'group' => 'sales'],
            ['name' => 'Manage Sales Leads', 'slug' => 'sales.leads.manage', 'group' => 'sales'],
            ['name' => 'View Sales Quotes', 'slug' => 'sales.quotes.view', 'group' => 'sales'],
            ['name' => 'Manage Sales Quotes', 'slug' => 'sales.quotes.manage', 'group' => 'sales'],
            ['name' => 'Approve Sales Quotes', 'slug' => 'sales.quotes.approve', 'group' => 'sales'],
            ['name' => 'View Sales Orders', 'slug' => 'sales.orders.view', 'group' => 'sales'],
            ['name' => 'Manage Sales Orders', 'slug' => 'sales.orders.manage', 'group' => 'sales'],
            ['name' => 'Approve Sales Orders', 'slug' => 'sales.orders.approve', 'group' => 'sales'],

            ['name' => 'View Inventory Stock', 'slug' => 'inventory.stock.view', 'group' => 'inventory'],
            ['name' => 'View Inventory Moves', 'slug' => 'inventory.moves.view', 'group' => 'inventory'],
            ['name' => 'Manage Inventory Moves', 'slug' => 'inventory.moves.manage', 'group' => 'inventory'],
            ['name' => 'View Cycle Counts', 'slug' => 'inventory.counts.view', 'group' => 'inventory'],
            ['name' => 'Manage Cycle Counts', 'slug' => 'inventory.counts.manage', 'group' => 'inventory'],
            ['name' => 'View Inventory Reordering', 'slug' => 'inventory.reordering.view', 'group' => 'inventory'],
            ['name' => 'Manage Inventory Reordering', 'slug' => 'inventory.reordering.manage', 'group' => 'inventory'],
            ['name' => 'Approve Inventory Adjustments', 'slug' => 'inventory.adjustments.approve', 'group' => 'inventory'],

            ['name' => 'View Purchase RFQs', 'slug' => 'purchasing.rfq.view', 'group' => 'purchasing'],
            ['name' => 'Manage Purchase RFQs', 'slug' => 'purchasing.rfq.manage', 'group' => 'purchasing'],
            ['name' => 'View Purchase Orders', 'slug' => 'purchasing.po.view', 'group' => 'purchasing'],
            ['name' => 'Manage Purchase Orders', 'slug' => 'purchasing.po.manage', 'group' => 'purchasing'],
            ['name' => 'Approve Purchase Orders', 'slug' => 'purchasing.po.approve', 'group' => 'purchasing'],
            ['name' => 'Manage Vendors', 'slug' => 'purchasing.vendors.manage', 'group' => 'purchasing'],

            ['name' => 'View Accounting Invoices', 'slug' => 'accounting.invoices.view', 'group' => 'accounting'],
            ['name' => 'Manage Accounting Invoices', 'slug' => 'accounting.invoices.manage', 'group' => 'accounting'],
            ['name' => 'Post Accounting Invoices', 'slug' => 'accounting.invoices.post', 'group' => 'accounting'],
            ['name' => 'View Accounting Payments', 'slug' => 'accounting.payments.view', 'group' => 'accounting'],
            ['name' => 'Manage Accounting Payments', 'slug' => 'accounting.payments.manage', 'group' => 'accounting'],
            ['name' => 'Approve Payment Reversals', 'slug' => 'accounting.payments.approve_reversal', 'group' => 'accounting'],
            ['name' => 'View Bank Reconciliation', 'slug' => 'accounting.bank_reconciliation.view', 'group' => 'accounting'],
            ['name' => 'Manage Bank Reconciliation', 'slug' => 'accounting.bank_reconciliation.manage', 'group' => 'accounting'],
            ['name' => 'View Manual Journals', 'slug' => 'accounting.manual_journals.view', 'group' => 'accounting'],
            ['name' => 'Manage Manual Journals', 'slug' => 'accounting.manual_journals.manage', 'group' => 'accounting'],
            ['name' => 'Post Manual Journals', 'slug' => 'accounting.manual_journals.post', 'group' => 'accounting'],
            ['name' => 'View Accounting Accounts', 'slug' => 'accounting.accounts.view', 'group' => 'accounting'],
            ['name' => 'View Accounting Journals', 'slug' => 'accounting.journals.view', 'group' => 'accounting'],
            ['name' => 'View Accounting Ledger', 'slug' => 'accounting.ledger.view', 'group' => 'accounting'],
            ['name' => 'View Accounting Statements', 'slug' => 'accounting.statements.view', 'group' => 'accounting'],
            ['name' => 'Close Accounting Period', 'slug' => 'accounting.period.close', 'group' => 'accounting'],

            ['name' => 'View Approval Requests', 'slug' => 'approvals.requests.view', 'group' => 'approvals'],
            ['name' => 'Manage Approval Requests', 'slug' => 'approvals.requests.manage', 'group' => 'approvals'],

            ['name' => 'View Projects', 'slug' => 'projects.projects.view', 'group' => 'projects'],
            ['name' => 'Manage Projects', 'slug' => 'projects.projects.manage', 'group' => 'projects'],
            ['name' => 'View Project Tasks', 'slug' => 'projects.tasks.view', 'group' => 'projects'],
            ['name' => 'Manage Project Tasks', 'slug' => 'projects.tasks.manage', 'group' => 'projects'],
            ['name' => 'Assign Project Tasks', 'slug' => 'projects.tasks.assign', 'group' => 'projects'],
            ['name' => 'View Project Timesheets', 'slug' => 'projects.timesheets.view', 'group' => 'projects'],
            ['name' => 'Manage Own Project Timesheets', 'slug' => 'projects.timesheets.manage_own', 'group' => 'projects'],
            ['name' => 'Manage Team Project Timesheets', 'slug' => 'projects.timesheets.manage_team', 'group' => 'projects'],
            ['name' => 'Approve Project Timesheets', 'slug' => 'projects.timesheets.approve', 'group' => 'projects'],
            ['name' => 'View Project Milestones', 'slug' => 'projects.milestones.view', 'group' => 'projects'],
            ['name' => 'Manage Project Milestones', 'slug' => 'projects.milestones.manage', 'group' => 'projects'],
            ['name' => 'View Project Billables', 'slug' => 'projects.billables.view', 'group' => 'projects'],
            ['name' => 'Manage Project Billables', 'slug' => 'projects.billables.manage', 'group' => 'projects'],
            ['name' => 'Approve Project Billables', 'slug' => 'projects.billables.approve', 'group' => 'projects'],
            ['name' => 'Create Project Invoice Drafts', 'slug' => 'projects.invoices.create', 'group' => 'projects'],
            ['name' => 'View Project Profitability', 'slug' => 'projects.profitability.view', 'group' => 'projects'],
            ['name' => 'View Project Recurring Billing', 'slug' => 'projects.recurring_billing.view', 'group' => 'projects'],
            ['name' => 'Manage Project Recurring Billing', 'slug' => 'projects.recurring_billing.manage', 'group' => 'projects'],
            ['name' => 'Run Project Recurring Billing', 'slug' => 'projects.recurring_billing.run', 'group' => 'projects'],

            ['name' => 'View Reports', 'slug' => 'reports.view', 'group' => 'reports'],
            ['name' => 'Export Reports', 'slug' => 'reports.export', 'group' => 'reports'],
            ['name' => 'View Webhooks', 'slug' => 'integrations.webhooks.view', 'group' => 'integrations'],
            ['name' => 'Manage Webhooks', 'slug' => 'integrations.webhooks.manage', 'group' => 'integrations'],
        ];

        foreach ($permissions as $permission) {
            Permission::updateOrCreate(
                ['slug' => $permission['slug']],
                [
                    'name' => $permission['name'],
                    'group' => $permission['group'],
                ]
            );
        }

        $allPermissionSlugs = Permission::query()->pluck('slug')->all();

        $roleBlueprints = [
            'owner' => [
                'name' => 'Owner',
                'description' => 'Full company access across modules and settings.',
                'data_scope' => 'company_records',
                'permissions' => $allPermissionSlugs,
            ],
            'member' => [
                'name' => 'Member',
                'description' => 'Baseline member access for day-to-day collaboration.',
                'data_scope' => 'own_records',
                'permissions' => [
                    'core.company.view',
                    'core.notifications.view',
                    'core.attachments.view',
                    'sales.leads.view',
                    'sales.quotes.view',
                    'sales.orders.view',
                    'inventory.stock.view',
                    'inventory.moves.view',
                    'inventory.reordering.view',
                    'purchasing.rfq.view',
                    'purchasing.po.view',
                    'accounting.invoices.view',
                    'accounting.payments.view',
                    'accounting.statements.view',
                    'projects.projects.view',
                    'projects.tasks.view',
                    'projects.timesheets.view',
                    'projects.timesheets.manage_own',
                    'projects.milestones.view',
                    'approvals.requests.view',
                    'reports.view',
                ],
            ],
            'operations_admin' => [
                'name' => 'Operations Admin',
                'description' => 'Operational admin access across sales, inventory, purchasing, and reports.',
                'data_scope' => 'company_records',
                'permissions' => [
                    'core.company.view',
                    'core.roles.view',
                    'core.users.manage',
                    'core.settings.manage',
                    'core.notifications.view',
                    'core.notifications.manage',
                    'core.attachments.view',
                    'core.attachments.manage',
                    'core.audit_logs.view',
                    'core.partners.view',
                    'core.partners.manage',
                    'core.contacts.view',
                    'core.contacts.manage',
                    'core.addresses.view',
                    'core.addresses.manage',
                    'core.products.view',
                    'core.products.manage',
                    'core.taxes.view',
                    'core.taxes.manage',
                    'core.uoms.view',
                    'core.uoms.manage',
                    'core.price_lists.view',
                    'core.price_lists.manage',
                    'sales.leads.view',
                    'sales.leads.manage',
                    'sales.quotes.view',
                    'sales.quotes.manage',
                    'sales.quotes.approve',
                    'sales.orders.view',
                    'sales.orders.manage',
                    'sales.orders.approve',
                    'inventory.stock.view',
                    'inventory.moves.view',
                    'inventory.moves.manage',
                    'inventory.reordering.view',
                    'inventory.reordering.manage',
                    'inventory.adjustments.approve',
                    'purchasing.rfq.view',
                    'purchasing.rfq.manage',
                    'purchasing.po.view',
                    'purchasing.po.manage',
                    'purchasing.po.approve',
                    'purchasing.vendors.manage',
                    'projects.projects.view',
                    'projects.projects.manage',
                    'projects.tasks.view',
                    'projects.tasks.manage',
                    'projects.tasks.assign',
                    'projects.timesheets.view',
                    'projects.timesheets.manage_team',
                    'projects.timesheets.approve',
                    'projects.milestones.view',
                    'projects.milestones.manage',
                    'projects.billables.view',
                    'projects.billables.manage',
                    'projects.recurring_billing.view',
                    'projects.recurring_billing.manage',
                    'projects.recurring_billing.run',
                    'projects.profitability.view',
                    'approvals.requests.view',
                    'approvals.requests.manage',
                    'reports.view',
                    'reports.export',
                    'integrations.webhooks.view',
                    'integrations.webhooks.manage',
                ],
            ],
            'project_manager' => [
                'name' => 'Project Manager',
                'description' => 'Project delivery oversight, team coordination, and service billing readiness.',
                'data_scope' => 'team_records',
                'permissions' => [
                    'core.company.view',
                    'core.notifications.view',
                    'core.attachments.view',
                    'core.attachments.manage',
                    'core.partners.view',
                    'projects.projects.view',
                    'projects.projects.manage',
                    'projects.tasks.view',
                    'projects.tasks.manage',
                    'projects.tasks.assign',
                    'projects.timesheets.view',
                    'projects.timesheets.manage_team',
                    'projects.timesheets.approve',
                    'projects.milestones.view',
                    'projects.milestones.manage',
                    'projects.billables.view',
                    'projects.billables.manage',
                    'projects.billables.approve',
                    'projects.invoices.create',
                    'projects.profitability.view',
                    'projects.recurring_billing.view',
                    'projects.recurring_billing.manage',
                    'projects.recurring_billing.run',
                    'reports.view',
                    'reports.export',
                ],
            ],
            'project_user' => [
                'name' => 'Project User',
                'description' => 'Assigned delivery execution for project tasks, timesheets, and milestones.',
                'data_scope' => 'own_records',
                'permissions' => [
                    'core.company.view',
                    'core.notifications.view',
                    'core.attachments.view',
                    'projects.projects.view',
                    'projects.tasks.view',
                    'projects.tasks.manage',
                    'projects.timesheets.view',
                    'projects.timesheets.manage_own',
                    'projects.milestones.view',
                ],
            ],
            'sales_manager' => [
                'name' => 'Sales Manager',
                'description' => 'Sales control, approvals, and team pipeline oversight.',
                'data_scope' => 'team_records',
                'permissions' => [
                    'core.company.view',
                    'core.notifications.view',
                    'core.partners.view',
                    'core.partners.manage',
                    'sales.leads.view',
                    'sales.leads.manage',
                    'sales.quotes.view',
                    'sales.quotes.manage',
                    'sales.quotes.approve',
                    'sales.orders.view',
                    'sales.orders.manage',
                    'sales.orders.approve',
                    'approvals.requests.view',
                    'reports.view',
                    'reports.export',
                    'integrations.webhooks.view',
                ],
            ],
            'sales_user' => [
                'name' => 'Sales User',
                'description' => 'Lead, quote, and order execution.',
                'data_scope' => 'own_records',
                'permissions' => [
                    'core.company.view',
                    'core.notifications.view',
                    'core.partners.view',
                    'sales.leads.view',
                    'sales.leads.manage',
                    'sales.quotes.view',
                    'sales.quotes.manage',
                    'sales.orders.view',
                    'sales.orders.manage',
                    'reports.view',
                ],
            ],
            'inventory_manager' => [
                'name' => 'Inventory Manager',
                'description' => 'Warehouse configuration, stock governance, and approvals.',
                'data_scope' => 'company_records',
                'permissions' => [
                    'core.company.view',
                    'core.notifications.view',
                    'core.products.view',
                    'core.products.manage',
                    'core.uoms.view',
                    'core.uoms.manage',
                    'inventory.stock.view',
                    'inventory.moves.view',
                    'inventory.moves.manage',
                    'inventory.counts.view',
                    'inventory.counts.manage',
                    'inventory.reordering.view',
                    'inventory.reordering.manage',
                    'inventory.adjustments.approve',
                    'approvals.requests.view',
                    'reports.view',
                    'reports.export',
                ],
            ],
            'warehouse_clerk' => [
                'name' => 'Warehouse Clerk',
                'description' => 'Receipts, picks, and fulfillment execution.',
                'data_scope' => 'team_records',
                'permissions' => [
                    'core.company.view',
                    'core.notifications.view',
                    'core.products.view',
                    'core.uoms.view',
                    'inventory.stock.view',
                    'inventory.moves.view',
                    'inventory.moves.manage',
                    'inventory.counts.view',
                    'inventory.counts.manage',
                    'inventory.reordering.view',
                ],
            ],
            'purchasing_manager' => [
                'name' => 'Purchasing Manager',
                'description' => 'RFQ and PO governance with spend oversight.',
                'data_scope' => 'company_records',
                'permissions' => [
                    'core.company.view',
                    'core.notifications.view',
                    'core.partners.view',
                    'core.partners.manage',
                    'core.products.view',
                    'core.taxes.view',
                    'inventory.reordering.view',
                    'inventory.reordering.manage',
                    'purchasing.rfq.view',
                    'purchasing.rfq.manage',
                    'purchasing.po.view',
                    'purchasing.po.manage',
                    'purchasing.po.approve',
                    'purchasing.vendors.manage',
                    'approvals.requests.view',
                    'approvals.requests.manage',
                    'reports.view',
                    'reports.export',
                ],
            ],
            'buyer' => [
                'name' => 'Buyer',
                'description' => 'RFQ and purchase order execution.',
                'data_scope' => 'team_records',
                'permissions' => [
                    'core.company.view',
                    'core.notifications.view',
                    'core.partners.view',
                    'core.products.view',
                    'core.taxes.view',
                    'inventory.reordering.view',
                    'purchasing.rfq.view',
                    'purchasing.rfq.manage',
                    'purchasing.po.view',
                    'purchasing.po.manage',
                ],
            ],
            'finance_manager' => [
                'name' => 'Finance Manager',
                'description' => 'Financial approvals, posting controls, and period close authority.',
                'data_scope' => 'company_records',
                'permissions' => [
                    'core.company.view',
                    'core.settings.manage',
                    'core.notifications.view',
                    'core.notifications.manage',
                    'core.audit_logs.view',
                    'core.partners.view',
                    'core.taxes.view',
                    'core.currencies.view',
                    'accounting.invoices.view',
                    'accounting.invoices.manage',
                    'accounting.invoices.post',
                    'accounting.payments.view',
                    'accounting.payments.manage',
                    'accounting.payments.approve_reversal',
                    'accounting.bank_reconciliation.view',
                    'accounting.bank_reconciliation.manage',
                    'accounting.manual_journals.view',
                    'accounting.manual_journals.manage',
                    'accounting.manual_journals.post',
                    'accounting.accounts.view',
                    'accounting.journals.view',
                    'accounting.ledger.view',
                    'accounting.statements.view',
                    'accounting.period.close',
                    'projects.projects.view',
                    'projects.timesheets.view',
                    'projects.milestones.view',
                    'projects.billables.view',
                    'projects.billables.manage',
                    'projects.billables.approve',
                    'projects.invoices.create',
                    'projects.profitability.view',
                    'projects.recurring_billing.view',
                    'projects.recurring_billing.manage',
                    'projects.recurring_billing.run',
                    'approvals.requests.view',
                    'approvals.requests.manage',
                    'reports.view',
                    'reports.export',
                ],
            ],
            'accountant' => [
                'name' => 'Accountant',
                'description' => 'AR/AP processing and reconciliation support.',
                'data_scope' => 'team_records',
                'permissions' => [
                    'core.company.view',
                    'core.notifications.view',
                    'core.partners.view',
                    'core.taxes.view',
                    'core.currencies.view',
                    'accounting.invoices.view',
                    'accounting.invoices.manage',
                    'accounting.invoices.post',
                    'accounting.payments.view',
                    'accounting.payments.manage',
                    'accounting.bank_reconciliation.view',
                    'accounting.bank_reconciliation.manage',
                    'accounting.manual_journals.view',
                    'accounting.manual_journals.manage',
                    'accounting.manual_journals.post',
                    'accounting.accounts.view',
                    'accounting.journals.view',
                    'accounting.ledger.view',
                    'accounting.statements.view',
                    'projects.projects.view',
                    'projects.timesheets.view',
                    'projects.milestones.view',
                    'projects.billables.view',
                    'projects.billables.manage',
                    'projects.invoices.create',
                    'projects.profitability.view',
                    'projects.recurring_billing.view',
                    'projects.recurring_billing.run',
                    'reports.view',
                ],
            ],
            'approver' => [
                'name' => 'Approver',
                'description' => 'Cross-module exception and threshold approvals.',
                'data_scope' => 'company_records',
                'permissions' => [
                    'core.company.view',
                    'core.notifications.view',
                    'sales.quotes.approve',
                    'sales.orders.approve',
                    'inventory.adjustments.approve',
                    'purchasing.po.approve',
                    'accounting.payments.approve_reversal',
                    'projects.projects.view',
                    'projects.billables.view',
                    'projects.timesheets.approve',
                    'projects.billables.approve',
                    'approvals.requests.view',
                    'approvals.requests.manage',
                    'reports.view',
                ],
            ],
            'auditor' => [
                'name' => 'Auditor',
                'description' => 'Read-only operational and governance visibility.',
                'data_scope' => 'read_all',
                'permissions' => [
                    'core.company.view',
                    'core.audit_logs.view',
                    'core.notifications.view',
                    'core.partners.view',
                    'core.contacts.view',
                    'core.addresses.view',
                    'core.products.view',
                    'core.taxes.view',
                    'core.currencies.view',
                    'core.uoms.view',
                    'core.price_lists.view',
                    'sales.leads.view',
                    'sales.quotes.view',
                    'sales.orders.view',
                    'inventory.stock.view',
                    'inventory.moves.view',
                    'inventory.reordering.view',
                    'purchasing.rfq.view',
                    'purchasing.po.view',
                    'accounting.invoices.view',
                    'accounting.payments.view',
                    'accounting.bank_reconciliation.view',
                    'accounting.manual_journals.view',
                    'accounting.accounts.view',
                    'accounting.journals.view',
                    'accounting.ledger.view',
                    'accounting.statements.view',
                    'projects.projects.view',
                    'projects.tasks.view',
                    'projects.timesheets.view',
                    'projects.milestones.view',
                    'projects.billables.view',
                    'projects.profitability.view',
                    'projects.recurring_billing.view',
                    'approvals.requests.view',
                    'reports.view',
                    'reports.export',
                ],
            ],
        ];

        foreach ($roleBlueprints as $slug => $blueprint) {
            $role = Role::updateOrCreate(
                ['slug' => $slug, 'company_id' => null],
                [
                    'name' => $blueprint['name'],
                    'description' => $blueprint['description'],
                    'data_scope' => $blueprint['data_scope'],
                    'company_id' => null,
                ]
            );

            $permissionIds = Permission::query()
                ->whereIn('slug', $blueprint['permissions'])
                ->pluck('id')
                ->all();

            $role->permissions()->sync($permissionIds);
        }
    }
}
