import InputError from '@/components/input-error';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import AppLayout from '@/layouts/app-layout';
import { Link, useForm } from '@inertiajs/react';

type Props = { mode: 'create' | 'edit'; title: string; description: string; submitUrl: string; method: 'post' | 'put'; form: { name: string; pay_frequency: string; start_date: string; end_date: string; payment_date: string; status: string } };
export default function PeriodForm({ mode, title, description, submitUrl, method, form: defaults }: Props) { const form = useForm(defaults); const submit = () => method === 'put' ? form.put(submitUrl) : form.post(submitUrl); return <AppLayout breadcrumbs={[{ title: 'HR', href: '/company/hr' }, { title: 'Payroll', href: '/company/hr/payroll' }, { title, href: submitUrl }]}><div className="max-w-3xl space-y-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-xl font-semibold">{title}</h1><p className="text-sm text-muted-foreground">{description}</p></div><Button variant="outline" asChild><Link href="/company/hr/payroll">Back to payroll</Link></Button></div><form className="grid gap-4 rounded-xl border p-4 md:grid-cols-2" onSubmit={(event) => { event.preventDefault(); submit(); }}><Field label="Name" error={form.errors.name}><Input value={form.data.name} onChange={(event) => form.setData('name', event.target.value)} /></Field><Field label="Pay frequency" error={form.errors.pay_frequency}><select className="h-9 rounded-md border border-input bg-background px-3 py-1 text-sm" value={form.data.pay_frequency} onChange={(event) => form.setData('pay_frequency', event.target.value)}><option value="monthly">Monthly</option><option value="biweekly">Biweekly</option><option value="weekly">Weekly</option></select></Field><Field label="Start date" error={form.errors.start_date}><Input type="date" value={form.data.start_date} onChange={(event) => form.setData('start_date', event.target.value)} /></Field><Field label="End date" error={form.errors.end_date}><Input type="date" value={form.data.end_date} onChange={(event) => form.setData('end_date', event.target.value)} /></Field><Field label="Payment date" error={form.errors.payment_date}><Input type="date" value={form.data.payment_date} onChange={(event) => form.setData('payment_date', event.target.value)} /></Field><Field label="Status" error={form.errors.status}><select className="h-9 rounded-md border border-input bg-background px-3 py-1 text-sm" value={form.data.status} onChange={(event) => form.setData('status', event.target.value)}><option value="draft">Draft</option><option value="open">Open</option><option value="processing">Processing</option><option value="closed">Closed</option></select></Field><div className="md:col-span-2"><Button type="submit" disabled={form.processing}>{mode === 'create' ? 'Create period' : 'Save period'}</Button></div></form></div></AppLayout>; }
function Field({ label, error, children }: { label: string; error?: string; children: React.ReactNode }) { return <div className="grid gap-2"><Label>{label}</Label>{children}<InputError message={error} /></div>; }
