import { Head, Link, useForm } from '@inertiajs/react';
import { BackLinkAction } from '@/components/navigation/back-link-action';
import { DataTableShell } from '@/components/shell/data-table-shell';
import {
    FilterField,
    FilterToolbar,
    FilterToolbarActions,
    FilterToolbarGrid,
} from '@/components/shell/filter-toolbar';
import { KpiStrip, MetricCard } from '@/components/shell/kpi-strip';
import { PageHeader } from '@/components/shell/page-header';
import { PaginationBar } from '@/components/shell/pagination-bar';
import { WorkspaceShell } from '@/components/shell/workspace-shell';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import {
    Table,
    TableBody,
    TableCell,
    TableHead,
    TableHeader,
    TableRow,
} from '@/components/ui/table';
import AppLayout from '@/layouts/app-layout';
import { companyModuleBreadcrumbs, companyModuleLinks } from '@/lib/page-navigation';

type Option = {
    id: string;
    label: string;
};

type LedgerEntryRow = {
    id: string;
    entry_group_uuid: string;
    transaction_date?: string | null;
    posting_reference: string;
    description: string;
    journal?: string | null;
    account?: string | null;
    source_action: string;
    counterparty_name?: string | null;
    debit: number;
    credit: number;
};

type Props = {
    filters: {
        start_date: string;
        end_date: string;
        journal_id: string;
        account_id: string;
        source_action: string;
    };
    summary: {
        entry_count: number;
        group_count: number;
        total_debit: number;
        total_credit: number;
    };
    journals: Option[];
    accounts: Option[];
    entries: {
        data: LedgerEntryRow[];
        links: { url: string | null; label: string; active: boolean }[];
    };
};

export default function AccountingLedgerIndex({
    filters,
    summary,
    journals,
    accounts,
    entries,
}: Props) {
    const form = useForm({
        start_date: filters.start_date ?? '',
        end_date: filters.end_date ?? '',
        journal_id: filters.journal_id ?? '',
        account_id: filters.account_id ?? '',
        source_action: filters.source_action ?? '',
    });

    return (
        <AppLayout
            breadcrumbs={companyModuleBreadcrumbs(companyModuleLinks.accounting, { title: 'General Ledger', href: '/company/accounting/ledger' },)}
        >
            <Head title="General Ledger" />

            <WorkspaceShell
                header={
                    <PageHeader
                        title="General ledger"
                        description="Every double-entry posting generated by invoices and payments."
                        actions={
                            <>
                                <BackLinkAction href="/company/accounting" label="Back to accounting
                                    " variant="outline" />
                                <Button variant="outline" asChild>
                                    <Link href="/company/accounting/journals">Journals</Link>
                                </Button>
                                <Button variant="outline" asChild>
                                    <Link href="/company/accounting/statements">
                                        Financial statements
                                    </Link>
                                </Button>
                            </>
                        }
                        meta={
                            <>
                                <span>{summary.entry_count} total entries</span>
                                <span className="h-1 w-1 rounded-full bg-[color:var(--text-muted)]" />
                                <span>{entries.data.length} rows on this page</span>
                            </>
                        }
                    />
                }
                kpis={
                    <KpiStrip>
                        <MetricCard label="Entries" value={String(summary.entry_count)} />
                        <MetricCard label="Posting groups" value={String(summary.group_count)} />
                        <MetricCard
                            label="Total debit"
                            value={summary.total_debit.toFixed(2)}
                            tone="info"
                        />
                        <MetricCard
                            label="Total credit"
                            value={summary.total_credit.toFixed(2)}
                            tone="info"
                        />
                    </KpiStrip>
                }
                table={
                    <DataTableShell>
                        <Table container={false} className="min-w-[1460px]">
                            <TableHeader>
                                <TableRow>
                                    <TableHead>Date</TableHead>
                                    <TableHead>Reference</TableHead>
                                    <TableHead>Group</TableHead>
                                    <TableHead>Journal</TableHead>
                                    <TableHead>Account</TableHead>
                                    <TableHead>Action</TableHead>
                                    <TableHead>Counterparty</TableHead>
                                    <TableHead>Description</TableHead>
                                    <TableHead className="text-right">Debit</TableHead>
                                    <TableHead className="text-right">Credit</TableHead>
                                </TableRow>
                            </TableHeader>
                            <TableBody>
                                {entries.data.length === 0 && (
                                    <TableRow>
                                        <TableCell
                                            className="py-12 text-center text-sm text-muted-foreground"
                                            colSpan={10}
                                        >
                                            No ledger entries found.
                                        </TableCell>
                                    </TableRow>
                                )}
                                {entries.data.map((entry) => (
                                    <TableRow key={entry.id}>
                                        <TableCell>{entry.transaction_date ?? '-'}</TableCell>
                                        <TableCell className="font-medium">
                                            {entry.posting_reference}
                                        </TableCell>
                                        <TableCell className="font-mono text-xs">
                                            {entry.entry_group_uuid.slice(0, 8)}
                                        </TableCell>
                                        <TableCell>{entry.journal ?? '-'}</TableCell>
                                        <TableCell>{entry.account ?? '-'}</TableCell>
                                        <TableCell className="capitalize">
                                            {entry.source_action.replace('_', ' ')}
                                        </TableCell>
                                        <TableCell>{entry.counterparty_name ?? '-'}</TableCell>
                                        <TableCell>{entry.description}</TableCell>
                                        <TableCell className="text-right font-medium tabular-nums">
                                            {entry.debit.toFixed(2)}
                                        </TableCell>
                                        <TableCell className="text-right font-medium tabular-nums">
                                            {entry.credit.toFixed(2)}
                                        </TableCell>
                                    </TableRow>
                                ))}
                            </TableBody>
                        </Table>
                    </DataTableShell>
                }
                pagination={<PaginationBar links={entries.links} />}
            >
                <FilterToolbar
                    onSubmit={(event) => {
                        event.preventDefault();
                        form.get('/company/accounting/ledger', {
                            preserveState: true,
                            preserveScroll: true,
                        });
                    }}
                >
                    <FilterToolbarGrid className="xl:grid-cols-5">
                        <FilterField label="Start date" htmlFor="start_date">
                            <Input
                                id="start_date"
                                type="date"
                                value={form.data.start_date}
                                onChange={(event) =>
                                    form.setData('start_date', event.target.value)
                                }
                            />
                        </FilterField>
                        <FilterField label="End date" htmlFor="end_date">
                            <Input
                                id="end_date"
                                type="date"
                                value={form.data.end_date}
                                onChange={(event) =>
                                    form.setData('end_date', event.target.value)
                                }
                            />
                        </FilterField>
                        <FilterField label="Journal" htmlFor="journal_id">
                            <select
                                id="journal_id"
                                className="h-10 rounded-[var(--radius-control)] border border-input bg-card px-3.5 py-2 text-sm text-foreground shadow-[var(--shadow-xs)] outline-none transition-[border-color,box-shadow,background-color] duration-150 focus-visible:border-[color:var(--border-strong)] focus-visible:ring-[3px] focus-visible:ring-ring/30"
                                value={form.data.journal_id}
                                onChange={(event) =>
                                    form.setData('journal_id', event.target.value)
                                }
                            >
                                <option value="">All journals</option>
                                {journals.map((journal) => (
                                    <option key={journal.id} value={journal.id}>
                                        {journal.label}
                                    </option>
                                ))}
                            </select>
                        </FilterField>
                        <FilterField label="Account" htmlFor="account_id">
                            <select
                                id="account_id"
                                className="h-10 rounded-[var(--radius-control)] border border-input bg-card px-3.5 py-2 text-sm text-foreground shadow-[var(--shadow-xs)] outline-none transition-[border-color,box-shadow,background-color] duration-150 focus-visible:border-[color:var(--border-strong)] focus-visible:ring-[3px] focus-visible:ring-ring/30"
                                value={form.data.account_id}
                                onChange={(event) =>
                                    form.setData('account_id', event.target.value)
                                }
                            >
                                <option value="">All accounts</option>
                                {accounts.map((account) => (
                                    <option key={account.id} value={account.id}>
                                        {account.label}
                                    </option>
                                ))}
                            </select>
                        </FilterField>
                        <FilterField label="Source action" htmlFor="source_action">
                            <select
                                id="source_action"
                                className="h-10 rounded-[var(--radius-control)] border border-input bg-card px-3.5 py-2 text-sm text-foreground shadow-[var(--shadow-xs)] outline-none transition-[border-color,box-shadow,background-color] duration-150 focus-visible:border-[color:var(--border-strong)] focus-visible:ring-[3px] focus-visible:ring-ring/30"
                                value={form.data.source_action}
                                onChange={(event) =>
                                    form.setData('source_action', event.target.value)
                                }
                            >
                                <option value="">All actions</option>
                                <option value="invoice_post">Invoice post</option>
                                <option value="invoice_cancel">Invoice cancel</option>
                                <option value="payment_post">Payment post</option>
                                <option value="payment_reverse">Payment reverse</option>
                            </select>
                        </FilterField>
                    </FilterToolbarGrid>

                    <FilterToolbarActions className="mt-4">
                        <Button type="submit">Apply filters</Button>
                        <Button type="button" variant="outline" asChild>
                            <Link href="/company/accounting/ledger">Reset</Link>
                        </Button>
                    </FilterToolbarActions>
                </FilterToolbar>
            </WorkspaceShell>
        </AppLayout>
    );
}
