import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import AppLayout from '@/layouts/app-layout';
import { Head, Link, useForm } from '@inertiajs/react';

type Option = {
    id: string;
    label: string;
};

type LedgerEntryRow = {
    id: string;
    entry_group_uuid: string;
    transaction_date?: string | null;
    posting_reference: string;
    description: string;
    journal?: string | null;
    account?: string | null;
    source_action: string;
    counterparty_name?: string | null;
    debit: number;
    credit: number;
};

type Props = {
    filters: {
        start_date: string;
        end_date: string;
        journal_id: string;
        account_id: string;
        source_action: string;
    };
    summary: {
        entry_count: number;
        group_count: number;
        total_debit: number;
        total_credit: number;
    };
    journals: Option[];
    accounts: Option[];
    entries: {
        data: LedgerEntryRow[];
        links: { url: string | null; label: string; active: boolean }[];
    };
};

export default function AccountingLedgerIndex({
    filters,
    summary,
    journals,
    accounts,
    entries,
}: Props) {
    const form = useForm({
        start_date: filters.start_date ?? '',
        end_date: filters.end_date ?? '',
        journal_id: filters.journal_id ?? '',
        account_id: filters.account_id ?? '',
        source_action: filters.source_action ?? '',
    });

    return (
        <AppLayout
            breadcrumbs={[
                { title: 'Company', href: '/company/dashboard' },
                { title: 'Accounting', href: '/company/accounting' },
                { title: 'General Ledger', href: '/company/accounting/ledger' },
            ]}
        >
            <Head title="General Ledger" />

            <div className="flex flex-wrap items-center justify-between gap-3">
                <div>
                    <h1 className="text-xl font-semibold">General ledger</h1>
                    <p className="text-sm text-muted-foreground">
                        Every double-entry posting generated by invoices and
                        payments.
                    </p>
                </div>
                <div className="flex flex-wrap gap-2">
                    <Button variant="outline" asChild>
                        <Link href="/company/accounting/journals">
                            Journals
                        </Link>
                    </Button>
                    <Button variant="outline" asChild>
                        <Link href="/company/accounting/statements">
                            Financial statements
                        </Link>
                    </Button>
                </div>
            </div>

            <div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-4">
                <MetricCard
                    label="Entries"
                    value={String(summary.entry_count)}
                />
                <MetricCard
                    label="Posting groups"
                    value={String(summary.group_count)}
                />
                <MetricCard
                    label="Total debit"
                    value={summary.total_debit.toFixed(2)}
                />
                <MetricCard
                    label="Total credit"
                    value={summary.total_credit.toFixed(2)}
                />
            </div>

            <form
                className="mt-6 rounded-xl border p-4"
                onSubmit={(event) => {
                    event.preventDefault();
                    form.get('/company/accounting/ledger', {
                        preserveState: true,
                        preserveScroll: true,
                    });
                }}
            >
                <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-5">
                    <div className="grid gap-2">
                        <Label htmlFor="start_date">Start date</Label>
                        <Input
                            id="start_date"
                            type="date"
                            value={form.data.start_date}
                            onChange={(event) =>
                                form.setData('start_date', event.target.value)
                            }
                        />
                    </div>
                    <div className="grid gap-2">
                        <Label htmlFor="end_date">End date</Label>
                        <Input
                            id="end_date"
                            type="date"
                            value={form.data.end_date}
                            onChange={(event) =>
                                form.setData('end_date', event.target.value)
                            }
                        />
                    </div>
                    <div className="grid gap-2">
                        <Label htmlFor="journal_id">Journal</Label>
                        <select
                            id="journal_id"
                            className="h-9 rounded-md border border-input bg-transparent px-3 py-1 text-sm"
                            value={form.data.journal_id}
                            onChange={(event) =>
                                form.setData('journal_id', event.target.value)
                            }
                        >
                            <option value="">All journals</option>
                            {journals.map((journal) => (
                                <option key={journal.id} value={journal.id}>
                                    {journal.label}
                                </option>
                            ))}
                        </select>
                    </div>
                    <div className="grid gap-2">
                        <Label htmlFor="account_id">Account</Label>
                        <select
                            id="account_id"
                            className="h-9 rounded-md border border-input bg-transparent px-3 py-1 text-sm"
                            value={form.data.account_id}
                            onChange={(event) =>
                                form.setData('account_id', event.target.value)
                            }
                        >
                            <option value="">All accounts</option>
                            {accounts.map((account) => (
                                <option key={account.id} value={account.id}>
                                    {account.label}
                                </option>
                            ))}
                        </select>
                    </div>
                    <div className="grid gap-2">
                        <Label htmlFor="source_action">Source action</Label>
                        <select
                            id="source_action"
                            className="h-9 rounded-md border border-input bg-transparent px-3 py-1 text-sm"
                            value={form.data.source_action}
                            onChange={(event) =>
                                form.setData(
                                    'source_action',
                                    event.target.value,
                                )
                            }
                        >
                            <option value="">All actions</option>
                            <option value="invoice_post">Invoice post</option>
                            <option value="invoice_cancel">
                                Invoice cancel
                            </option>
                            <option value="payment_post">Payment post</option>
                            <option value="payment_reverse">
                                Payment reverse
                            </option>
                        </select>
                    </div>
                </div>
                <div className="mt-4 flex flex-wrap gap-2">
                    <Button type="submit">Apply filters</Button>
                    <Button type="button" variant="outline" asChild>
                        <Link href="/company/accounting/ledger">Reset</Link>
                    </Button>
                </div>
            </form>

            <div className="mt-6 overflow-x-auto rounded-xl border">
                <table className="w-full min-w-[1460px] text-sm">
                    <thead className="bg-muted/60 text-left">
                        <tr>
                            <th className="px-4 py-3 font-medium">Date</th>
                            <th className="px-4 py-3 font-medium">Reference</th>
                            <th className="px-4 py-3 font-medium">Group</th>
                            <th className="px-4 py-3 font-medium">Journal</th>
                            <th className="px-4 py-3 font-medium">Account</th>
                            <th className="px-4 py-3 font-medium">Action</th>
                            <th className="px-4 py-3 font-medium">
                                Counterparty
                            </th>
                            <th className="px-4 py-3 font-medium">
                                Description
                            </th>
                            <th className="px-4 py-3 font-medium">Debit</th>
                            <th className="px-4 py-3 font-medium">Credit</th>
                        </tr>
                    </thead>
                    <tbody className="divide-y">
                        {entries.data.length === 0 && (
                            <tr>
                                <td
                                    className="px-4 py-8 text-center text-muted-foreground"
                                    colSpan={10}
                                >
                                    No ledger entries found.
                                </td>
                            </tr>
                        )}
                        {entries.data.map((entry) => (
                            <tr key={entry.id}>
                                <td className="px-4 py-3">
                                    {entry.transaction_date ?? '-'}
                                </td>
                                <td className="px-4 py-3 font-medium">
                                    {entry.posting_reference}
                                </td>
                                <td className="px-4 py-3 font-mono text-xs">
                                    {entry.entry_group_uuid.slice(0, 8)}
                                </td>
                                <td className="px-4 py-3">
                                    {entry.journal ?? '-'}
                                </td>
                                <td className="px-4 py-3">
                                    {entry.account ?? '-'}
                                </td>
                                <td className="px-4 py-3 capitalize">
                                    {entry.source_action.replace('_', ' ')}
                                </td>
                                <td className="px-4 py-3">
                                    {entry.counterparty_name ?? '-'}
                                </td>
                                <td className="px-4 py-3">
                                    {entry.description}
                                </td>
                                <td className="px-4 py-3">
                                    {entry.debit.toFixed(2)}
                                </td>
                                <td className="px-4 py-3">
                                    {entry.credit.toFixed(2)}
                                </td>
                            </tr>
                        ))}
                    </tbody>
                </table>
            </div>

            {entries.links.length > 1 && (
                <div className="mt-6 flex flex-wrap gap-2">
                    {entries.links.map((link) => (
                        <Link
                            key={link.label}
                            href={link.url ?? '#'}
                            className={`rounded-md border px-3 py-1 text-sm ${
                                link.active
                                    ? 'border-primary text-primary'
                                    : 'text-muted-foreground'
                            } ${!link.url ? 'pointer-events-none opacity-50' : ''}`}
                            dangerouslySetInnerHTML={{ __html: link.label }}
                        />
                    ))}
                </div>
            )}
        </AppLayout>
    );
}

function MetricCard({ label, value }: { label: string; value: string }) {
    return (
        <div className="rounded-xl border p-4">
            <p className="text-xs tracking-wide text-muted-foreground uppercase">
                {label}
            </p>
            <p className="mt-2 text-2xl font-semibold">{value}</p>
        </div>
    );
}
